name: Test and Deploy

on:
  push:
    branches:
      - main
jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Test Utils
        run: npm run test-utils

        # Use github marketplace
  test-app:
    runs-on: ubuntu-latest
    needs: test-utils
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: test_db
          postgresql user: test_user
          postgresql password: password
      - name: Install Dependencies
        run: npm install
      - name: Test App
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=password npm run test-app

  deploy:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: cr-nc-news
          heroku_email: ${{secrets.HEROKU_EMAIL}}
